name: Build and Deploy
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      deployment-target:
        description: 'Target for deployment'
        required: true
        default: 'production' # Provide a default value or adjust as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.2"

      - name: Install Dependencies
        run: npm install
 
      - name: Build Website
        run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "unnecessary"
 
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz --delete . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET_DIRECTORY }}
